global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flower
    static_configs:
      - targets: ['d-flower:5555']
  - job_name: exporter
    static_configs:
      - targets: ['d-exporter:9808']