version: '3.9'

services:
  danaides:
    container_name: danaides
    # image: python:3
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ${ENV_FILE}
    working_dir: /app
    ports:
      - 4444:4444
    volumes:
      - ./app:/app
    networks:
      - ergopad-net
    # command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/app" -- python -m main
    command: tail /dev/null -f

  danaides_api:
    container_name: danaides_api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ${ENV_FILE}
    working_dir: /app
    ports:
      - 7000:7000
      - 7001:8000 # default port for python -m http.server
    volumes:
      - ./app:/app
    networks:
      - ergopad-net
    # command: uvicorn api:app --reload --workers 1 --reload-dir /app --host 0.0.0.0 --port ${API_PORT} --proxy-headers --use-colors
    command: tail /dev/null -f

networks:
  ergopad-net:
    external: true
