version: '3.9'

services:
  d-alembic:
    container_name: d-alembic
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
     - .:/app
    networks:
      - ergopad-net
    command: tail /dev/null -f
    # command: alembic upgrade head

networks:
  ergopad-net:
    external: true
